name: Update Built Cache State
description: TODO
inputs:
  system:
    description: "Target system"
    required: true
    default: "x86_64-linux"
  
  aws-bucket:
    description: "AWS S3 Bucket"
    required: true
    default: "versions-cache"
  
  aws_access_key_id:
    required: true
    description: TODO
  aws_secret_access_key:
    required: true
    description: TODO
  git_token:
    required: false
    description: TODO
  substituter:
    required: false
    description: TODO


runs:
  using: composite
  steps:
    - id: config
      shell: bash
      run: |
        # FIXME: make generic over github instances (GH Enterprise)
        # TODO: use `?ref=..`
        FLAKE_REF="github:${{github.repository}}/${{github.ref_name}}#packages.${{inputs.system}}"
        FLAKE_REF="$(echo ${FLAKE_REF} | tr / _)"
        DB_PATH="$FLAKE_REF.db"
        EVAL_RESULT="$FLAKE_REF.json"

        echo "::set-output name=flake-ref::${FLAKE_REF}"
        echo "::set-output name=db-path::${DB_PATH}"
        echo "::set-output name=eval-result::${EVAL_RESULT}"

    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          access-tokens = ${{ inputs.git_token }}
          experimental-features = nix-command flakes

    - name: copy cachedb from s3
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        AWS_REGION: us-east-1
      run: nix shell nixpkgs\#awscli2 -c aws s3 cp s3://${{inputs.aws-bucket}}/${{steps.config.outputs.db-path}} ./${{steps.config.outputs.db-path}} || true

    - name: db permissions
      shell: bash
      run: |
        [[ -e ${{steps.config.outputs.db-path}} ]] || exit 0

        sudo chown runner ${{steps.config.outputs.db-path}} 
        sudo chmod 664 ${{steps.config.outputs.db-path}}

    - name: Eval linux
      shell: bash
      run: nix run .#eval ./#packages.${{inputs.system}} | tee ${{steps.config.outputs.eval-result}}

    - name: Build cache linux
      shell: bash
      run: |
        SUBSTITUTER_FLAG=""
        [[ -z "${{inputs.substituter}}" ]] || SUBSTITUTER_FLAG="--substituter ${{inputs.substituter}}"
        nix run .#checkCache -- --debug ${SUBSTITUTER_FLAG} -u -d ${{steps.config.outputs.db-path}} activate < ${{steps.config.outputs.eval-result}}


    - name: copy update cachedb overwrite back to s3
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        AWS_REGION: us-east-1
      run: nix shell nixpkgs\#awscli2 -c aws s3 cp ./${{steps.config.outputs.db-path}} s3://${{inputs.aws-bucket}}/${{steps.config.outputs.db-path}}

    - name: copy update eval cache overwrite back to s3
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        AWS_REGION: us-east-1
      run: nix shell nixpkgs\#awscli2 -c aws s3 cp ./${{steps.config.outputs.eval-result}} s3://${{inputs.aws-bucket}}/${{steps.config.outputs.eval-result}}
